extends Node

signal spirit_stones_changed(amount)
signal currency_changed(currency_type: String, amount)
signal hall_unlocked(hall_id: int)
signal hall_leveled(hall_id: int, new_level: int)
signal hall_cycle_completed(hall_id: int, revenue)
signal elder_hired(elder_id: int)
signal milestone_reached(hall_id: int, level: int)
signal dao_path_selected(path_id: int)
signal dao_spell_activated(path_id: int)
signal dao_spell_ended(path_id: int)
signal alchemy_crafted(item_id: int)
signal buff_expired(buff_id: String)
signal ascension_started()
signal ascension_completed(hdp_gained: int)
signal challenge_started(challenge_id: int)
signal challenge_completed(challenge_id: int)
signal treasure_spawned()
signal treasure_collected(value)
signal meditate_tapped()
signal tab_changed(tab_name: String)
signal game_loaded()
signal game_saved()
signal offline_earnings_calculated(earnings, duration_seconds: float)
